<?php

/**
 * Implements hook_preprocess_HOOK().
 */
function sevenalter_toolbar_preprocess_html(&$variables) {
  // Add sevenalter admin class to the body.
  if (_sevenalter_toolbar_is_access()) {
    $variables['attributes']['class'][] = 'admin-toolbar-sevenalter';
  }
}

/**
 * Implements hook_page_attachments_alter().
 */
function sevenalter_toolbar_page_attachments_alter(array &$page) {
  // Attaches css assets globally.
  if (_sevenalter_toolbar_is_access()) {
    $page['#attached']['library'][] = 'sevenalter_toolbar/sevenalter_toolbar';
  }
}

// function sevenalter_toolbar_library_info_alter(&$libraries, $extension) {
//   if (_sevenalter_toolbar_is_access()) {
//       // Verify existence of admin_toolbar
//       if ($extension == "admin_toolbar") {
//         // Unset the CSS of admin_toolbar
//         unset($libraries['toolbar.tree']['css']['theme']['css/admin.toolbar.css']);
//       }
  
//       // Verify existence of toolbar
//       if ($extension == "toolbar") {
//         // Unset the CSS of core toolbar main style
//         unset($libraries['toolbar']['css']['theme']['css/toolbar.theme.css']);
//       }
//   }
// }

/**
 * Helper function for checking user permission.
 *
 * We reallly only want to add styling and changes to toolbar when the user has access
 * Returns TRUE or FALSE.
 */
function _sevenalter_toolbar_is_access() {
  $user = \Drupal::currentUser();
  return $user->hasPermission('access toolbar');
}
